version: '3.8'

services:
  Share-AI-express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Share-AI-express
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - Share-AI-data:/usr/src/app/data
    environment:
      - NODE_ENV=production
      - PORT=8888
    networks:
      - Share-AI-network

volumes:
  Share-AI-data:
    driver: local

networks:
  Share-AI-network:
    driver: bridge
